### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Hellcode48** [scottwinkler/cocoapebbles-book#1]
Seems like everytime I create a book using the web ui, nothing happens and when I import a book I cannot see it in the web ui. I do have both ports open. No errors in console

**Comment by scottwinkler** [comment]
Sorry you are having this issue, I would be happy to help you work through this. My initial guess is that it is a permissions issue -- perhaps the plugin is not able to write files to the /plugins/Book/books directory. Could you please verify that the books are indeed not being populated in this directory? Here is an example book:

 ```
{"id":"d6649cc6","title":"The Illiad - Homer","pages":["\n\n\nThe Illiad - Homer","SING, O GODDESS, the anger of Achilles son of Peleus, that brought countless ills upon the Achaeans. Many a brave soul did it send hurrying down to Hades, and many a hero did it yield a prey to dogs and vultures, for so were the counsels of Jove fulfilled ","from the day on which the son of Atreus, king of men, and great Achilles, first fell out with one another"],"author":"Scott"}
```

If this does not address your problem, then I can add more detailed logging to help identify the issue

**Comment by Hellcode48** [comment]
Its still not working even though I changed the perms to 777.

**Comment by scottwinkler** [comment]
Okay -- i would like to debug this issue. Let me write some print statements for info/errors to help identify the issue. Are you able to build this project yourself or would you like me to send you a new jar file?

**Comment by scottwinkler** [comment]
Also can you verify that indeed the web app is running on port 8080 and the api is running on port 9000? these should be in the logs 

edit: when creating a book, even if it fails to create it should say "Creating book with id: <>" in the logs. Do you get this? If so it would indicate that at least the server is running

edit2: i am interested in the fact that the import book doesnt work. even if the api server isn't running, it should still create the book anyways. And if there is an IOException, it is already caught and printed so it should be in the logs. Could you reload the plugins and copy/paste the logs here?

**Comment by Hellcode48** [comment]
Hellcode48 issued server command: /plugman load Book


17:27:21

[Book]: Enabling Book v1.0
[Book]: Initializing file server

WARN
 
12/13/2018 17:27:21

17:27:21

58191252 [Server thread]: INFO org.eclipse.jetty.util.log - Logging initialized @58230869ms to org.eclipse.jetty.util.log.Slf4jLog


17:27:22

58191801 [Server thread]: INFO org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 1.8.0_191-b12
58191921 [Server thread]: INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.h.ContextHandler@696a8e3{/,null,AVAILABLE}
58191952 [Server thread]: INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@f2fe99f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
58191952 [Server thread]: INFO org.eclipse.jetty.server.Server - Started @58231570ms

INFO
 
12/13/2018 17:27:22

17:27:22

[Book]: File server running on port: 8080!
[Book]: Initializing jersey application


17:27:23

[Book]: Application started on port: 9000!

**Comment by Hellcode48** [comment]
When I create a book in the UI, nothing happens and no errors or anything in console

**Comment by scottwinkler** [comment]
Have you checked the console in the browser? Could be a CORS issue. It still doesnt explain why the import is failing... actually could you try "/book list"? Also try Chrome for your browser if not already using

**Comment by Hellcode48** [comment]
It is CORS issue

**Comment by scottwinkler** [comment]
Good at least I know what the problem is now. I am going to see if I can merge the file server with the api. That would avoid any possibility for a CORS issue. Theres really no good reason for them to be separate anyways

**Comment by scottwinkler** [comment]
@xH3LLRAIZ3Rx I believe I have solved the CORS problem. I combined the two servers so now both the static files and the api are being served from the same port (8080). Please download this new jar file and let me know if it works for you: https://s3.amazonaws.com/tfe-configurations/cocoapebbles-book-1.0.jar. If so then I will upload my changes to github and bump the version

**Comment by Hellcode48** [comment]
Ok I tested, no longer getting CORS error, but nothing still shows in web ui, in console it shows: TypeError: "NetworkError when attempting to fetch resource."

**Comment by scottwinkler** [comment]
This should be an easy fix. It
I think its trying to get it from the old port, 9000 when it should be getting it from 8080. Could you please delete the entire /plugins/book/web folder and reload plugin?

**Comment by Hellcode48** [comment]
I deleted the entire folder then loaded plugin

**Comment by scottwinkler** [comment]
Is it working? If not, could you please copy the logs from the browser console? Also in the browser, type in the url "[your server ip]:8080/books" and report what you get?

**Comment by Hellcode48** [comment]
from the /books I get: 
[{"id":"079c8b3f","title":"sdfdsfsdf","pages":["sdfdfsdfsdfsdf"],"author":"Hellcode48"}] which is correct, but it seems to not just show in the main 8080

The logs of console:
 action @@router/LOCATION_CHANGE @ 21:53:26.629 redux-logger.js:389
 prev state 
Object { books: {…}, router: {…} }
redux-logger.js:400
 action     
Object { type: "@@router/LOCATION_CHANGE", payload: {…} }
redux-logger.js:404
 next state 
Object { books: {…}, router: {…} }
redux-logger.js:413
 action BOOKS_LOADING @ 21:53:26.643 redux-logger.js:389
 prev state 
Object { books: {…}, router: {…} }
redux-logger.js:400
 action     
Object { type: "BOOKS_LOADING", payload: true }
redux-logger.js:404
 next state 
Object { books: {…}, router: {…} }
redux-logger.js:413
TypeError: "NetworkError when attempting to fetch resource."
	G http://.net:8080/static/js/main.4cd784d3.chunk.js:1:7541
	r http://.net:8080/static/js/1.9df11de9.chunk.js:1:42531
	dispatch http://.net:8080/static/js/1.9df11de9.chunk.js:1:50695
	G http://.net:8080/static/js/main.4cd784d3.chunk.js:1:7499
	r http://.net:8080/static/js/1.9df11de9.chunk.js:1:42531
	f http://.net:8080/static/js/1.9df11de9.chunk.js:1:49779
	componentWillMount http://.net:8080/static/js/main.4cd784d3.chunk.js:1:6097
	Ro http://.net:8080/static/js/1.9df11de9.chunk.js:1:162552
	Xo http://.net:8080/static/js/1.9df11de9.chunk.js:1:170070
	ti http://.net:8080/static/js/1.9df11de9.chunk.js:1:175188
	Ti http://.net:8080/static/js/1.9df11de9.chunk.js:1:189248
	ji http://.net:8080/static/js/1.9df11de9.chunk.js:1:189594
	fa http://.net:8080/static/js/1.9df11de9.chunk.js:1:194266
	ca http://.net:8080/static/js/1.9df11de9.chunk.js:1:193920
	Ii http://.net:8080/static/js/1.9df11de9.chunk.js:1:192432
	ba http://.net:8080/static/js/1.9df11de9.chunk.js:1:200882
	ga http://.net:8080/static/js/1.9df11de9.chunk.js:1:200936
	render http://.net:8080/static/js/1.9df11de9.chunk.js:1:204758
	ka http://.net:8080/static/js/1.9df11de9.chunk.js:1:202569
	va http://.net:8080/static/js/1.9df11de9.chunk.js:1:200018
	ka http://.net:8080/static/js/1.9df11de9.chunk.js:1:202504
	render http://.net:8080/static/js/1.9df11de9.chunk.js:1:205739
	5577 http://.net:8080/static/js/main.4cd784d3.chunk.js:1:9357
	f http://.net:8080/:1:513
	5428 http://.net:8080/static/js/main.4cd784d3.chunk.js:1:89
	f http://.net:8080/:1:513
	a http://.net:8080/:1:387
	e http://.net:8080/:1:250
	<anonymous> http://.net:8080/static/js/main.4cd784d3.chunk.js:1:47
home.js:81:26
 action BOOKS_LOADING @ 21:53:26.675 redux-logger.js:389
 prev state 
Object { books: {…}, router: {…} }
redux-logger.js:400
 action     
Object { type: "BOOKS_LOADING", payload: false }
redux-logger.js:404
 next state 
Object { books: {…}, router: {…} }
redux-logger.js:413

**Comment by scottwinkler** [comment]
Thank you for continued patience in debugging this, it is a 1.0 release so I am glad to work through these problems with you as it will help make the plugin more robust. It looks like the plugin is not able to determine the server ip. Can you please verify that server-ip is set in the server.properties file of your minecraft server. Also you may have a caching issue with the old static files, and might need to either clear the browser data or use incognito in chrome.

edit: server-ip could also be the fqdn of your server, if using a custom domain name. E.g. `server-ip=https://example.com ` Now that i merged the two servers together, I can make it so you dont need to specify the server-ip as it can be determined dynamically. I will add this to the list of improvements for the next version.
edit 2: i forgot to mention that because of another bug, in order for the change to be take affect, after updating the server-ip, go ahead and delete the /plugin/book/web folder again, then reload the plugin

**Comment by scottwinkler** [comment]
@xH3LLRAIZ3Rx I have been working to fix a lot of the problems that were identified. Here is the changelog:
1) server-ip is no longer required to be set. the web app discovers its ip at runtime
2) you shouldnt need to delete the /plugins/web folder anymore. there is now a version.txt file that will automatically clear and update the /plugins/web folder if the version doesn't match

Please download this new jar file and let me know how it goes.
https://s3-us-west-2.amazonaws.com/cocoapebbles-minecraft-plugins/cocoapebbles-books-1.1.jar

**Comment by Hellcode48** [comment]
Just tested and it works perfectly :D
